version: '3'
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      custom_network:
        ipv4_address: 10.10.1.1
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      custom_network:
        ipv4_address: 10.10.1.2
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
     - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./sq.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      custom_network:
        ipv4_address: 10.10.1.3

volumes:
  db:
    driver: local
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
